type TagCodesType = {
  [key: string]: {
    [key: string]: string;
  };
};

export const EN_TAG_CODES = ["Brand", "Collection"];

export const TAG_CODES: TagCodesType = {
  Accessories: {
    Saucers: "Podmisky",
    Watering: "Zavlažování",
    Wheels: "Kolečka",
    Liners: "Vložky",
    "Water level indicators": "Ukazatel hladiny vody",
    Base: "Základ",
    Systems: "Systémy",
    "Other accessories": "Další příslušenství",
    Hydroculture: "Hydrokultura",
    "Soil culture": "Půdní kultura",
    Nutrients: "Živiny",
    Pesticide: "Pesticid",
    Leafshine: "Lesk na listy",
    Other: "Ostatní",
    Transport: "Transport",
    Equipments: "Vybavení",
    Feet: "Nohy",
  },
  ArtificialGroup: {
    Alocasia: "Alokázie",
    Bamboo: "Bambus",
    Buxus: "Buxus",
    Calathea: "Kalátea",
    "Cissus (ivy)": "Cissus (břečťan)",
    Ficus: "Fikus",
    Olea: "Olea",
    Orchids: "Orchideje",
    Philodendron: "Filodendron",
    Dracaena: "Dračinec",
    Grasses: "Trávy",
    Palms: "Palmy",
    Sansevieria: "Sansevieria",
    Ferns: "Kapradiny",
    Zamioculcas: "Zamioculcas",
    Other: "Ostatní",
    Agapanthus: "Agapant",
    Strelitzia: "Strelície",
  },
  ArtificialShape: {
    Bush: "Keř",
    Tuft: "Trs",
    Hanging: "Závěsný",
    Ball: "Koule",
    Other: "Ostatní",
    Branched: "Rozvětvený",
    Stem: "Stonek",
  },
  ColourArtificial: {
    White: "Bílá",
    Yellow: "Žlutá",
    Orange: "Oranžová",
    Other: "Ostatní",
    Pink: "Růžová",
    Violet: "Fialová",
    "Multi-colored": "Vícebarevná",
    Red: "Červená",
  },
  Finish: {
    Natural: "Přírodní povrchová úprava",
    "High gloss": "Vysoký lesk",
    "Satin gloss": "Satinový lesk",
    Matt: "Matný",
    Metallic: "Kovový",
    Polished: "Leštěný",
    Lacquered: "Lakovaný",
    Structure: "Strukturovaný",
    Glazed: "Glazovaný",
  },
  Location: {
    Indoor: "Vnitřní",
    Outdoor: "Venkovní",
  },
  MaterialArtificial: {
    "Fire retardant": "Požáruvzdorný",
    "UV resistant": "Odolný proti UV záření",
    "Water resistant": "Voděodolný",
    "Including decorative pot": "Včetně dekorativního květináče",
    "Recycled material": "Recyklovatelný materiál",
  },
  Material: {
    "Terra Cotta": "Terra Cotta",
    Natural: "Přírodní materiál",
    Sandstone: "Pískovec",
    Metal: "Lov",
    Ficonstone: "Ficonstone",
    Polyresin: "Polyresin",
    Polystone: "Polystone",
    Fiberstone: "Fiberstone",
    Wood: "Dřevo",
    "Stainless steel": "Nerezová ocel",
    Aluminium: "Hliník",
    Composite: "Kompozit",
    Syntetic: "Syntetika",
    Ceramics: "Keramika",
    Fiberclay: "Vláknitá hlína",
  },
  MaterialProperties: {
    "Raised base": "Zvýšený základ",
    "Including wheels": "S kolečky",
    "Fire retardant": "Oheň odolný",
    "Scratch and break resistant": "Odolný proti poškrábání a lámání",
    "Recycled material": "Recyklovaný materiál",
    Handmade: "Ručně vyráběný",
    "Frost resistant": "Odolný proti mrazu",
    "UV resistant": "Odolný proti UV",
    Waterproof: "Vodotěsný",
    "With drainage hole": "S odtokovým otvorem",
  },
  Shape: {
    Cube: "Krychle",
    Boat: "Loď",
    Vulcan: "Vulkan",
    "With feet": "S nohama",
    Square: "Čtverec",
    Rectangle: "Obdélník",
    Kubis: "Kubis",
    Bowl: "Miska",
    Darcy: "Darcy",
    Coppa: "Coppa",
    Amphore: "Amfora",
    Globe: "Koule",
    Cylinder: "Válec",
    Balloon: "Balón",
    Oval: "Ovál",
    "Hanging basket": "Visací koš",
  },
  ColourPlanter: {
    White: "Bílá",
    Black: "Černá",
    Grey: "Šedá",
    Brown: "Hnědá",
    Beige: "Bežová",
    Red: "Červená",
    Orange: "Oranžová",
    Yellow: "Žlutá",
    Green: "Zelená",
    Blue: "Modrá",
    Purple: "Fialová",
    Pink: "Růžová",
    Multicolour: "Vícebarevná",
    Anthracite: "Antracit",
    Bronze: "Bronz",
    Gold: "Zlatá",
    Silver: "Stříbrná",
    Copper: "Měděná",
  },
  ProductFeatures: {
    "Raised bottom": "Falešné dno",
    "Including wheels": "S kolečky",
    "Including liner": "S vložkou",
  },
};

export const ITEM_HEIGHTS = [
  {
    min: 0,
    max: 40,
    tag: "0 - 40 cm",
  },
  {
    min: 41,
    max: 60,
    tag: "40 - 60 cm",
  },
  {
    min: 61,
    max: 80,
    tag: "60 - 80 cm",
  },
  {
    min: 81,
    max: 120,
    tag: "80 - 120 cm",
  },
];

export const ITEM_DIAMETERS = [
  {
    min: 0,
    max: 10,
    tag: "Do 10 cm",
  },
  {
    min: 11,
    max: 20,
    tag: "11 - 20 cm",
  },
  {
    min: 21,
    max: 30,
    tag: "21 - 30 cm",
  },
  {
    min: 31,
    max: 40,
    tag: "31 - 40 cm",
  },
  {
    min: 41,
    max: 50,
    tag: "41 - 50 cm",
  },
  {
    min: 51,
    max: 60,
    tag: "51 - 60 cm",
  },
  {
    min: 61,
    max: 70,
    tag: "61 - 70 cm",
  },
  {
    min: 71,
    max: 80,
    tag: "71 - 80 cm",
  },
  {
    min: 81,
    max: 90,
    tag: "81 - 90 cm",
  },
  {
    min: 91,
    max: 100,
    tag: "91 - 100 cm",
  },
  {
    min: 101,
    max: 110,
    tag: "101 - 110 cm",
  },
  {
    min: 111,
    max: 120,
    tag: "111 - 120 cm",
  },
];

export const SIZES = [
  " XXXS ",
  " XXS ",
  " XS ",
  " S ",
  " M ",
  " L ",
  " XL ",
  " XXL ",
  " XXXL ",
  " XXXS, ",
  " XXS, ",
  " XS, ",
  " S, ",
  " M, ",
  " L, ",
  " XL, ",
  " XXL, ",
  " XXXL, ",
];

export const MAIN_SPECS = [
  {
    label: "Ø Průměr vnější",
    value: "Diameter",
    unit: "cm",
  },
  {
    label: "Ø Průměr vnitřní",
    value: "Opening",
    unit: "cm",
  },
  {
    label: "Výška",
    value: "Height",
    unit: "cm",
  },
  {
    label: "Hloubka",
    value: "Depth",
    unit: "cm",
  },
  {
    label: "Hmotnost",
    value: "Weight",
    unit: "kg",
  },
  {
    label: "Objem",
    value: "Volume",
    unit: "l",
  },
];

export const TAGS = [
  { tagCode: "Shape", label: "Tvar" },
  { tagCode: "ArtificialShape", label: "Tvar" },
  { tagCode: "ColourArtificial", label: "Barva" },
  { tagCode: "ColourPlanter", value: "Barva" },
  { tagCode: "Finish", label: "Povrch" },
  { tagCode: "Location", label: "Použití" },
  { tagCode: "Material", label: "Materiál" },
  { tagCode: "MaterialArtificial", label: "Materiál" },
  { tagCode: "MaterialProperties", label: "Extra Vlastnosti" },
  { tagCode: "ProductFeatures", label: "Jiné Vlastnosti" },
  { tagCode: "Accessories", label: "Příslušenství" },
  { tagCode: "ArtificialGroup", label: "Skupina" },
  { tagCode: "Brand", label: "Značka" },
];
