export const TAG_CODES = {
  Location: {
    Indoor: "vnitřní",
    Outdoor: "venkovní",
  },
  Finish: {
    Natural: "přírodní povrchová úprava",
    "High gloss": "vysoký lesk",
    "Satin gloss": "satinový lesk",
    Matt: "matný",
    Metallic: "kovový",
    Polished: "leštěný",
    Lacquered: "lakovaný",
    Glazed: "glazovaný",
  },
  Material: {
    "Terra Cotta": "terra totta",
    Natural: "přírodní materiál",
    Sandstone: "pískovec",
    Metal: "kov",
    Ficonstone: "ficonstone",
    Polyresin: "polyresin",
    Polystone: "polystone",
    Fiberstone: "fiberstone",
    Wood: "dřevo",
    "Stainless steel": "nerezová ocel",
    Aluminium: "hliník",
    Composite: "kompozit",
    Syntetic: "syntetika",
    Ceramics: "keramika",
    Fiberclay: "vláknitá hlína",
  },
  MaterialProperties: {
    "Raised base": "zvýšený základ",
    "Including wheels": "s kolečky",
    "Fire retardant": "oheň odolný",
    "Scratch and break resistant": "odolný proti poškrábání a lámání",
    "Recycled material": "recyklovaný materiál",
    Handmade: "ručně vyráběný",
    "Frost resistant": "odolný proti mrazu",
    "UV resistant": "odolný proti UV",
    Waterproof: "vodotěsný",
    "With drainage hole": "s odtokovým otvorem",
  },
  Shape: {
    Cube: "krychle",
    Boat: "loď",
    Vulcan: "vulkan",
    "With feet": "s nohama",
    Square: "čtverec",
    Rectangle: "obdélník",
    Kubis: "kubis",
    Bowl: "miska",
    Darcy: "darcy",
    Coppa: "coppa",
    Amphore: "amfora",
    Globe: "koule",
    Cylinder: "válec",
    Balloon: "balón",
    Oval: "ovál",
    "Hanging basket": "visací koš",
  },
  ColourPlanter: {
    White: "bílá",
    Black: "černá",
    Grey: "šedá",
    Brown: "hnědá",
    Beige: "bežová",
    Red: "červená",
    Orange: "oranžová",
    Yellow: "žlutá",
    Green: "zelená",
    Blue: "modrá",
    Purple: "fialová",
    Pink: "růžová",
    Multicolour: "vícebarevná",
    Anthracite: "antracit",
    Bronze: "bronz",
    Gold: "zlatá",
    Silver: "stříbrná",
    Copper: "měděná",
  },
};
