# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a6b10b41eb0aa1d2a9ac72b7f04e5a5c"
application_url = "https://guards-border-nursing-keno.trycloudflare.com"
embedded = true
name = "nieuwkoop-v2"
handle = "nieuwkoop-v2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://guards-border-nursing-keno.trycloudflare.com/auth/callback",
  "https://guards-border-nursing-keno.trycloudflare.com/auth/shopify/callback",
  "https://guards-border-nursing-keno.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
