export const GiftCardItemsData = [
  {
    id: 487817672276298560,
    admin_graphql_api_id: "gid://shopify/LineItem/487817672276298554",
    current_quantity: 1,
    fulfillable_quantity: 1,
    fulfillment_service: "manual",
    fulfillment_status: null,
    gift_card: false,
    grams: 100,
    name: "Aviator sunglasses",
    price: "500",
    price_set: {
      shop_money: { amount: "500", currency_code: "CZK" },
      presentment_money: { amount: "500", currency_code: "CZK" },
    },
    product_exists: true,
    product_id: 788032119674292900,
    properties: [],
    quantity: 1,
    requires_shipping: true,
    sales_line_item_group_id: null,
    sku: "GIFTCARD-500",
    taxable: true,
    title: "Aviator sunglasses",
    total_discount: "0.00",
    total_discount_set: { shop_money: [Object], presentment_money: [Object] },
    variant_id: null,
    variant_inventory_management: null,
    variant_title: null,
    vendor: null,
    tax_lines: [],
    duties: [],
    discount_allocations: [],
  },
  {
    id: 976318377106520300,
    admin_graphql_api_id: "gid://shopify/LineItem/976318377106520349",
    attributed_staffs: [],
    current_quantity: 1,
    fulfillable_quantity: 1,
    fulfillment_service: "manual",
    fulfillment_status: null,
    gift_card: false,
    grams: 1000,
    name: "Mid-century lounger",
    price: "500",
    price_set: {
      shop_money: { amount: "1000", currency_code: "CZK" },
      presentment_money: { amount: "1000", currency_code: "CZK" },
    },
    product_exists: true,
    product_id: 788032119674292900,
    properties: [],
    quantity: 1,
    requires_shipping: true,
    sales_line_item_group_id: null,
    sku: "GIFTCARD-1000",
    taxable: true,
    title: "Mid-century lounger",
    total_discount: "0.00",
    total_discount_set: { shop_money: [Object], presentment_money: [Object] },
    variant_id: null,
    variant_inventory_management: null,
    variant_title: null,
    vendor: null,
    tax_lines: [],
    duties: [],
    discount_allocations: [],
  },
];
