const Hydroculture = [
  {
    Itemcode: "1KEFO5T10",
    DeliveryTimeInDays: 1,
    PalletQuantity: null,
    Description: "Kentia (Howea) forsteriana",
    ItemDescription_NL: "Kentia (Howea) forsteriana",
    ItemStatus: "A",
    SalesPackage_NL: "Stuks   ",
    SalesPackage_DE: "Stück",
    SalesPackage_EN: "Unit",
    SalesPackage_FR: "Pièce",
    Salesprice: 41.2,
    MainGroupCode: "100",
    MainGroupDescription_NL: "Planten",
    MainGroupDescription_DE: "Planten",
    MainGroupDescription_EN: "Planten",
    MainGroupDescription_FR: "Planten",
    ProductGroupCode: "100",
    ProductGroupDescription_NL: "Hydrocultuur",
    ProductGroupDescription_DE: "Hydrokultur",
    ProductGroupDescription_EN: "Hydroculture",
    ProductGroupDescription_FR: "Hydroculture",
    GroupDescription: "HYH",
    GroupDescription_NL: "Hydrocultuur standaard",
    GroupDescription_DE: "Hydrokultur standard",
    GroupDescription_EN: "Hydroculture standard",
    GroupDescription_FR: "Hydroculture standard",
    MaterialGroupCode: null,
    MaterialGroupDescription_NL: null,
    MaterialGroupDescription_DE: null,
    MaterialGroupDescription_EN: null,
    MaterialGroupDescription_FR: null,
    ItemDescription_EN: "Kentia (Howea) forsteriana",
    ItemDescription_DE: "Kentia (Howea) forsteriana",
    ItemDescription_FR: "Kentia (Howea) forsteriana",
    GTINCode: "8718233006639",
    IsStockItem: true,
    Warehouse: "A",
    ItemVariety_NL: "Toef 6pp",
    ItemVariety_DE: "Tuff 6pp",
    ItemVariety_EN: "Tuft 6pp",
    ItemVariety_FR: "Touffe 6pp",
    PotSize: "18/19",
    ItemPictureName: "1KEFO5T10.png",
    ItemPictureSysmodified: "2021-07-20T13:07:22",
    Content_Ltr: null,
    PlantPassportCode: null,
    Diameter: 0,
    Length: 0,
    Width: 50,
    Height: 100,
    Depth: 0,
    Opening: 0,
    IsOffer: false,
    ShowOnWebsite: true,
    Sysmodified: "2023-10-17T08:54:33.507",
    SalesOrderSize: 1,
    DiameterCulturePot: 18,
    HeightCulturePot: 19,
    Weight: 8.24,
    CitesListed: false,
    CountryOfOrigin: "NL",
    CountryOfProvenance: "NL",
    FytoListed: false,
    HSCode: 6029099,
    HSCodeUK: "0602909990",
    LeafSize: "> 40",
    QuantityPallet: 0,
    QuantityTrolley: 66,
    LocationIcon_DE: "Schatten",
    LocationIcon_EN: "shade",
    LocationIcon_FR: "ombre ",
    LocationIcon_NL: "schaduw",
    LocationUsagePlanters_DE: null,
    LocationUsagePlanters_EN: null,
    LocationUsagePlanters_FR: null,
    LocationUsagePlanters_NL: null,
    onlyShipTo: null,
    PEC: 0,
    isProduction: 0,
    Tags: [
      {
        Code: "Blooming",
        Values: [
          {
            Description_NL: "Zonder bloem",
            Description_DE: "Ohne Blume",
            Description_EN: "Without flower",
            Description_FR: "Sans fleur",
          },
        ],
      },
      {
        Code: "LeafColourTint",
        Values: [
          {
            Description_NL: "Groen",
            Description_DE: "Grün",
            Description_EN: "Green",
            Description_FR: "Verte",
          },
        ],
      },
      {
        Code: "LeafShape",
        Values: [
          {
            Description_NL: "Samengesteld ",
            Description_DE: "Mehrfach",
            Description_EN: "Multiple",
            Description_FR: "Multiple",
          },
        ],
      },
      {
        Code: "LeafSize",
        Values: [
          {
            Description_NL: "> 40",
            Description_DE: "> 40",
            Description_EN: "> 40",
            Description_FR: "> 40",
          },
        ],
      },
      {
        Code: "LocationLight",
        Values: [
          {
            Description_NL: "750",
            Description_DE: "750",
            Description_EN: "750",
            Description_FR: "750",
          },
        ],
      },
      {
        Code: "LocationLight1",
        Values: [
          {
            Description_NL: "1000",
            Description_DE: "1000",
            Description_EN: "1000",
            Description_FR: "1000",
          },
        ],
      },
      {
        Code: "LocationLight2",
        Values: [
          {
            Description_NL: "70",
            Description_DE: "70",
            Description_EN: "70",
            Description_FR: "70",
          },
        ],
      },
      {
        Code: "PlantCategory",
        Values: [
          {
            Description_NL: "Palmen & Palmachtigen",
            Description_DE: "Palmen",
            Description_EN: "Palms & Palm trees",
            Description_FR: "Palmiers ",
          },
        ],
      },
      {
        Code: "PlantShape",
        Values: [
          {
            Description_NL: "Toef",
            Description_DE: "Tuff",
            Description_EN: "Tuft",
            Description_FR: "Touffe",
          },
        ],
      },
      {
        Code: "PlantVariety",
        Values: [
          {
            Description_NL: "Kentia (howea forsteriana)",
            Description_DE: "Kentia (howea forsteriana)",
            Description_EN: "Kentia (howea forsteriana)",
            Description_FR: "Kentia (howea forsteriana)",
          },
        ],
      },
      {
        Code: "SubstrateType",
        Values: [
          {
            Description_NL: "Hydrokorrels",
            Description_DE: "Blähton",
            Description_EN: "Hydro granules",
            Description_FR: "Hydro-granulés",
          },
        ],
      },
      {
        Code: "Temperature",
        Values: [
          {
            Description_NL: "15",
            Description_DE: "15",
            Description_EN: "15",
            Description_FR: "15",
          },
        ],
      },
    ],
  },
];
