const Soilculture = [
  {
    Itemcode: "4AEMLHA15",
    DeliveryTimeInDays: 1,
    PalletQuantity: null,
    Description: "Aeschynanthus 'Mona Lisa'",
    ItemDescription_NL: "Aeschynanthus 'Mona Lisa'",
    ItemStatus: "A",
    SalesPackage_NL: "Stuks   ",
    SalesPackage_DE: "Stück",
    SalesPackage_EN: "Unit",
    SalesPackage_FR: "Pièce",
    Salesprice: 9.75,
    MainGroupCode: "100",
    MainGroupDescription_NL: "Planten",
    MainGroupDescription_DE: "Planten",
    MainGroupDescription_EN: "Planten",
    MainGroupDescription_FR: "Planten",
    ProductGroupCode: "200",
    ProductGroupDescription_NL: "Grondcultuur",
    ProductGroupDescription_DE: "Erdkultur",
    ProductGroupDescription_EN: "Soilculture",
    ProductGroupDescription_FR: "Terre culture",
    GroupDescription: "PCO",
    GroupDescription_NL: "Potplanten",
    GroupDescription_DE: "Topfpflanzen",
    GroupDescription_EN: "Potplants",
    GroupDescription_FR: "Plantes en terre",
    MaterialGroupCode: null,
    MaterialGroupDescription_NL: null,
    MaterialGroupDescription_DE: null,
    MaterialGroupDescription_EN: null,
    MaterialGroupDescription_FR: null,
    ItemDescription_EN: "Aeschynanthus 'Mona Lisa'",
    ItemDescription_DE: "Aeschynanthus 'Mona Lisa'",
    ItemDescription_FR: "Aeschynanthus 'Mona Lisa'",
    GTINCode: "8718233297365",
    IsStockItem: true,
    Warehouse: "A",
    ItemVariety_NL: "Hanger",
    ItemVariety_DE: "Ampel",
    ItemVariety_EN: "Hanger",
    ItemVariety_FR: "Retombant",
    PotSize: "15",
    ItemPictureName: "4AEMLHA15.png",
    ItemPictureSysmodified: "2023-07-18T11:33:21",
    Content_Ltr: null,
    PlantPassportCode: null,
    Diameter: 0,
    Length: 0,
    Width: 30,
    Height: 40,
    Depth: 0,
    Opening: 0,
    IsOffer: false,
    ShowOnWebsite: true,
    Sysmodified: "2023-10-17T08:54:33.507",
    SalesOrderSize: 1,
    DiameterCulturePot: 15,
    HeightCulturePot: 13,
    Weight: 2.633,
    CitesListed: false,
    CountryOfOrigin: null,
    CountryOfProvenance: null,
    FytoListed: false,
    HSCode: 6029099,
    HSCodeUK: "0602909990",
    LeafSize: "2-5",
    QuantityPallet: 0,
    QuantityTrolley: 140,
    LocationIcon_DE: "Halbschatten",
    LocationIcon_EN: "partial shade",
    LocationIcon_FR: "mi-ombre",
    LocationIcon_NL: "half-schaduw",
    LocationUsagePlanters_DE: null,
    LocationUsagePlanters_EN: null,
    LocationUsagePlanters_FR: null,
    LocationUsagePlanters_NL: null,
    onlyShipTo: null,
    PEC: 0,
    isProduction: 0,
    Tags: [
      {
        Code: "LeafColourTint",
        Values: [
          {
            Description_NL: "Groen",
            Description_DE: "Grün",
            Description_EN: "Green",
            Description_FR: "Verte",
          },
        ],
      },
      {
        Code: "LeafShape",
        Values: [
          {
            Description_NL: "Ovaal",
            Description_DE: "Oval",
            Description_EN: "Oval",
            Description_FR: "Ovale",
          },
        ],
      },
      {
        Code: "LeafSize",
        Values: [
          {
            Description_NL: "2-5",
            Description_DE: "2-5",
            Description_EN: "2-5",
            Description_FR: "2-5",
          },
        ],
      },
      {
        Code: "LocationLight",
        Values: [
          {
            Description_NL: "1000",
            Description_DE: "1000",
            Description_EN: "1000",
            Description_FR: "1000",
          },
        ],
      },
      {
        Code: "LocationLight1",
        Values: [
          {
            Description_NL: "1000",
            Description_DE: "1000",
            Description_EN: "1000",
            Description_FR: "1000",
          },
        ],
      },
      {
        Code: "LocationLight2",
        Values: [
          {
            Description_NL: "40",
            Description_DE: "40",
            Description_EN: "40",
            Description_FR: "40",
          },
        ],
      },
      {
        Code: "PlantCategory",
        Values: [
          {
            Description_NL: "Overige planten",
            Description_DE: "Andere Pflanzen",
            Description_EN: "Other plants",
            Description_FR: "Autre plantes",
          },
        ],
      },
      {
        Code: "PlantShape",
        Values: [
          {
            Description_NL: "Hang",
            Description_DE: "Ranker",
            Description_EN: "Hang",
            Description_FR: "Retombante",
          },
        ],
      },
      {
        Code: "PlantVariety",
        Values: [
          {
            Description_NL: "Overige planten",
            Description_DE: "Andere Pflanzen",
            Description_EN: "Other plants",
            Description_FR: "Autre plantes",
          },
        ],
      },
      {
        Code: "SubstrateType",
        Values: [
          {
            Description_NL: "Grond",
            Description_DE: "Erde",
            Description_EN: "Soil",
            Description_FR: "Terre",
          },
        ],
      },
      {
        Code: "Temperature",
        Values: [
          {
            Description_NL: "15",
            Description_DE: "15",
            Description_EN: "15",
            Description_FR: "15",
          },
        ],
      },
    ],
  },
];
