export const products = [
    {
         "Itemcode": "1ASELTU40",
         "DeliveryTimeInDays": 999,
         "PalletQuantity": null,
         "Description": "Aspidistra elatior",
         "ItemDescription_NL": "Aspidistra elatior",
         "ItemStatus": "E",
         "SalesPackage_NL": "Stuks   ",
         "SalesPackage_DE": "Stück",
         "SalesPackage_EN": "Unit",
         "SalesPackage_FR": "Pièce",
         "Salesprice": 36.5,
         "MainGroupCode": "100",
         "MainGroupDescription_NL": "Planten",
         "MainGroupDescription_DE": "Planten",
         "MainGroupDescription_EN": "Planten",
         "MainGroupDescription_FR": "Planten",
         "ProductGroupCode": "100",
         "ProductGroupDescription_NL": "Hydrocultuur",
         "ProductGroupDescription_DE": "Hydrokultur",
         "ProductGroupDescription_EN": "Hydroculture",
         "ProductGroupDescription_FR": "Hydroculture",
         "GroupDescription": "HYH",
         "GroupDescription_NL": "Hydrocultuur standaard",
         "GroupDescription_DE": "Hydrokultur standard",
         "GroupDescription_EN": "Hydroculture standard",
         "GroupDescription_FR": "Hydroculture standard",
         "MaterialGroupCode": null,
         "MaterialGroupDescription_NL": null,
         "MaterialGroupDescription_DE": null,
         "MaterialGroupDescription_EN": null,
         "MaterialGroupDescription_FR": null,
         "ItemDescription_EN": "Aspidistra elatior",
         "ItemDescription_DE": "Aspidistra elatior",
         "ItemDescription_FR": "Aspidistra elatior",
         "GTINCode": "8718233001214",
         "IsStockItem": true,
         "Warehouse": "A",
         "ItemVariety_NL": "Toef",
         "ItemVariety_DE": "Tuff",
         "ItemVariety_EN": "Tuft",
         "ItemVariety_FR": "Touffe",
         "PotSize": "22/19",
         "ItemPictureName": "1ASELTU40.png",
         "ItemPictureSysmodified": null,
         "Content_Ltr": null,
         "PlantPassportCode": null,
         "Diameter": 0.0,
         "Length": 0.0,
         "Width": 40.0,
         "Height": 90.0,
         "Depth": 0.0,
         "Opening": 0.0,
         "IsOffer": false,
         "ShowOnWebsite": false,
         "Sysmodified": "2023-10-17T09:02:11.007",
         "SalesOrderSize": 1,
         "DiameterCulturePot": 22.0,
         "HeightCulturePot": 19.0,
         "Weight": 7.3,
         "Tags": []
     },
     {
         "Itemcode": "1DIBATU25",
         "DeliveryTimeInDays": 60,
         "PalletQuantity": null,
         "Description": "Dieffenbachia seguine 'Banana'",
         "ItemDescription_NL": "Dieffenbachia seguine 'Banana'",
         "ItemStatus": "D",
         "SalesPackage_NL": "Stuks   ",
         "SalesPackage_DE": "Stück",
         "SalesPackage_EN": "Unit",
         "SalesPackage_FR": "Pièce",
         "Salesprice": 36.0,
         "MainGroupCode": "100",
         "MainGroupDescription_NL": "Planten",
         "MainGroupDescription_DE": "Planten",
         "MainGroupDescription_EN": "Planten",
         "MainGroupDescription_FR": "Planten",
         "ProductGroupCode": "100",
         "ProductGroupDescription_NL": "Hydrocultuur",
         "ProductGroupDescription_DE": "Hydrokultur",
         "ProductGroupDescription_EN": "Hydroculture",
         "ProductGroupDescription_FR": "Hydroculture",
         "GroupDescription": "HYH",
         "GroupDescription_NL": "Hydrocultuur standaard",
         "GroupDescription_DE": "Hydrokultur standard",
         "GroupDescription_EN": "Hydroculture standard",
         "GroupDescription_FR": "Hydroculture standard",
         "MaterialGroupCode": null,
         "MaterialGroupDescription_NL": null,
         "MaterialGroupDescription_DE": null,
         "MaterialGroupDescription_EN": null,
         "MaterialGroupDescription_FR": null,
         "ItemDescription_EN": "Dieffenbachia seguine 'Banana'",
         "ItemDescription_DE": "Dieffenbachia seguine 'Banana'",
         "ItemDescription_FR": "Dieffenbachia seguine 'Banana'",
         "GTINCode": "8718233357014",
         "IsStockItem": true,
         "Warehouse": "A",
         "ItemVariety_NL": "Toef",
         "ItemVariety_DE": "Tuff",
         "ItemVariety_EN": "Tuft",
         "ItemVariety_FR": "Touffe",
         "PotSize": "25/19",
         "ItemPictureName": "1DIBATU25.png",
         "ItemPictureSysmodified": null,
         "Content_Ltr": null,
         "PlantPassportCode": null,
         "Diameter": 0.0,
         "Length": 0.0,
         "Width": 70.0,
         "Height": 80.0,
         "Depth": 0.0,
         "Opening": 0.0,
         "IsOffer": false,
         "ShowOnWebsite": true,
         "Sysmodified": "2023-10-17T09:02:11.007",
         "SalesOrderSize": 1,
         "DiameterCulturePot": 25.0,
         "HeightCulturePot": 19.0,
         "Weight": 7.2,
         "Tags": []
     },
     {
         "Itemcode": "1FIEMRS22",
         "DeliveryTimeInDays": 60,
         "PalletQuantity": null,
         "Description": "Ficus elastica 'Makana'",
         "ItemDescription_NL": "Ficus elastica 'Makana'",
         "ItemStatus": "D",
         "SalesPackage_NL": "Stuks   ",
         "SalesPackage_DE": "Stück",
         "SalesPackage_EN": "Unit",
         "SalesPackage_FR": "Pièce",
         "Salesprice": 37.5,
         "MainGroupCode": "100",
         "MainGroupDescription_NL": "Planten",
         "MainGroupDescription_DE": "Planten",
         "MainGroupDescription_EN": "Planten",
         "MainGroupDescription_FR": "Planten",
         "ProductGroupCode": "100",
         "ProductGroupDescription_NL": "Hydrocultuur",
         "ProductGroupDescription_DE": "Hydrokultur",
         "ProductGroupDescription_EN": "Hydroculture",
         "ProductGroupDescription_FR": "Hydroculture",
         "GroupDescription": "HYH",
         "GroupDescription_NL": "Hydrocultuur standaard",
         "GroupDescription_DE": "Hydrokultur standard",
         "GroupDescription_EN": "Hydroculture standard",
         "GroupDescription_FR": "Hydroculture standard",
         "MaterialGroupCode": null,
         "MaterialGroupDescription_NL": null,
         "MaterialGroupDescription_DE": null,
         "MaterialGroupDescription_EN": null,
         "MaterialGroupDescription_FR": null,
         "ItemDescription_EN": "Ficus elastica 'Makana'",
         "ItemDescription_DE": "Ficus elastica 'Makana'",
         "ItemDescription_FR": "Ficus elastica 'Makana'",
         "GTINCode": "8718233400000",
         "IsStockItem": true,
         "Warehouse": "A",
         "ItemVariety_NL": "Stam",
         "ItemVariety_DE": "Stamm",
         "ItemVariety_EN": "Stem",
         "ItemVariety_FR": "Tige",
         "PotSize": "22/19",
         "ItemPictureName": "1FIEMRS22.png",
         "ItemPictureSysmodified": null,
         "Content_Ltr": null,
         "PlantPassportCode": null,
         "Diameter": 0.0,
         "Length": 0.0,
         "Width": 40.0,
         "Height": 120.0,
         "Depth": 0.0,
         "Opening": 0.0,
         "IsOffer": false,
         "ShowOnWebsite": true,
         "Sysmodified": "2023-10-17T09:02:11.007",
         "SalesOrderSize": 1,
         "DiameterCulturePot": 22.0,
         "HeightCulturePot": 19.0,
         "Weight": 7.5,
         "Tags": []
     },
     {
        "Itemcode": "1SALABP10",
        "DeliveryTimeInDays": 80,
        "PalletQuantity": null,
        "Description": "Sansevieria trifasciata 'Laurentii'",
        "ItemDescription_NL": "Sansevieria trifasciata 'Laurentii'",
        "ItemStatus": "B",
        "SalesPackage_NL": "Stuks   ",
        "SalesPackage_DE": "Stück",
        "SalesPackage_EN": "Unit",
        "SalesPackage_FR": "Pièce",
        "Salesprice": 7.95,
        "MainGroupCode": "100",
        "MainGroupDescription_NL": "Planten",
        "MainGroupDescription_DE": "Planten",
        "MainGroupDescription_EN": "Planten",
        "MainGroupDescription_FR": "Planten",
        "ProductGroupCode": "100",
        "ProductGroupDescription_NL": "Hydrocultuur",
        "ProductGroupDescription_DE": "Hydrokultur",
        "ProductGroupDescription_EN": "Hydroculture",
        "ProductGroupDescription_FR": "Hydroculture",
        "GroupDescription": "HYH",
        "GroupDescription_NL": "Hydrocultuur standaard",
        "GroupDescription_DE": "Hydrokultur standard",
        "GroupDescription_EN": "Hydroculture standard",
        "GroupDescription_FR": "Hydroculture standard",
        "MaterialGroupCode": null,
        "MaterialGroupDescription_NL": null,
        "MaterialGroupDescription_DE": null,
        "MaterialGroupDescription_EN": null,
        "MaterialGroupDescription_FR": null,
        "ItemDescription_EN": "Sansevieria trifasciata 'Laurentii'",
        "ItemDescription_DE": "Sansevieria trifasciata 'Laurentii'",
        "ItemDescription_FR": "Sansevieria trifasciata 'Laurentii'",
        "GTINCode": "8718233008558",
        "IsStockItem": true,
        "Warehouse": "A",
        "ItemVariety_NL": "Toef",
        "ItemVariety_DE": "Tuff",
        "ItemVariety_EN": "Tuft",
        "ItemVariety_FR": "Touffe",
        "PotSize": "15/19",
        "ItemPictureName": "1SALABP10.png",
        "ItemPictureSysmodified": null,
        "Content_Ltr": null,
        "PlantPassportCode": null,
        "Diameter": 0.0,
        "Length": 0.0,
        "Width": 15.0,
        "Height": 55.0,
        "Depth": 0.0,
        "Opening": 0.0,
        "IsOffer": false,
        "ShowOnWebsite": false,
        "Sysmodified": "2023-10-17T09:02:11.007",
        "SalesOrderSize": 1,
        "DiameterCulturePot": 15.0,
        "HeightCulturePot": 19.0,
        "Weight": 1.59,
        "Tags": []
    }
    ]